name: GitHub Action repo
on: push
jobs:    
  action-demo:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the codee
        uses: actions/checkout@v4
      - name: Print index.html
        run: cat index.html
